---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_omnibus_install_options: -P <%= ENV['PROJECT_NAME'] %>
  chef_omnibus_root: /opt/<%= ENV['PROJECT_NAME'] %>
  require_chef_omnibus: <%= ENV['PROJECT_VERSION'] || 'latest' %>

verifier:
  chef_omnibus_root: /opt/<%= ENV['PROJECT_NAME'] %>

platforms:
  - name: ubuntu-14.04

suites:
  - name: acceptance
